# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: lonewolf003
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

Step 3. Running GitHub Actions

Once you've added the code above and committed it, head to your Actions tab. Under "Workflows", you should see the "Generate Snake" Action you created above.

Workflow

Click "Run Workflow" and watch your workflow run. You can even expand your workflow and see what's happening in real time.

Running Actions

Once your workflow has finished running, you should have received a green âœ… "build" checkmark. If so, this means your Action is working nicely. If not, you'll have to go through the code and see where the errors are. The "build" status should give you some indication of where your errors lie. You can also compare it with the yaml file on my GitHub Profile README.

Build green

If you have the green "build" âœ… then you should be good to go. Head back to your repo's "Code" directory, and change your branch to "output". Here you'll find the two versions of your contribution graph with the snake eating it: a *.gif and a *.svg. The good thing about these files is the file is rewritten over itself every time the Action runs. Thus, your contribution graph will always be up to date.

CodeOutput
Step 4. Adding a contribution-eating snake to your profile

Now the final set is to add this to your profile. Grab the file location of your *.gif. It should be something like:

https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif

Add this to your profile by copying the file location onto a new line in your markdown file:

![snake gif](https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif)

Now you should have a really cool looking snake eating your contributions!

SnakeEating

Hopefully this guide was helpful for you and gives you a good base to start building and adding more Actions on your profile. What have you been adding to your GitHub Profile README? Other there other cool Actions I should be looking at?
Git Good (9 Part Series)
1 Using the GitHub CLI to update your repo
2 How to create and pin a gist on GitHub
... 5 more parts...
8 How to use GitHub Pages to host your website, even with multiple repos
9 How to create a Profile README for your Organisation
Top comments (25)
pic
Â 
kushaltanna24 profile image
â€¢
Jun 3

Work fine.! Here is mine - KushalTanna24
Reply
Â 
msoftware profile image
â€¢
Jul 9 '21

Great tutorial! Works for me.
Here's mine - github.com/msoftware
Reply
Â 
gustavohgmartins profile image
â€¢
Sep 3 '21

Awsome! How did you change the background-color?
Reply
Â 
mishmanners profile image
â€¢
Sep 3 '21

I didn't change the background colour. It's a .png/.svg image, meaning the background is transparent. It looks dark on mine because I have dark mode enabled on GitHub. You can enable it by clicking Settings --> Appearance --> choosing your mode.
Thread
Â 
gustavohgmartins profile image
â€¢
Sep 3 '21

Thank you! actually I was using the .gif version, so I switched to the .svg one and voilÃ¡
Thread
Â 
mishmanners profile image
â€¢
Sep 3 '21

Awesome! Glad to be of help ğŸ˜„
Reply
Â 
bpolaswar profile image
â€¢
Oct 17 '21

Great worked for me. See github.com/bpolaswar
Thanks.
Reply
Â 
zieldecastro profile image
â€¢
Sep 15 '21 â€¢ Edited on Sep 15

It does not work for me. Can someone help me?
github.com/zieldecastro
instagram.com/zieldecastro/
Reply
Â 
viveeeeeek profile image
â€¢
Oct 3 '21

Awesome!
Reply
Â 
shasank27 profile image
â€¢
Aug 8 '21 â€¢ Edited on Aug 8

Great tutorial!
But can anyone help me, its not showing all my contributions
github.com/shasank27/shasank27
Reply
Â 
mishmanners profile image
â€¢
Sep 6 '21 â€¢ Edited on Sep 6

Hey Shasank. I can't see it on your profile, but to show all contributions, you need to make sure all contributions are turned on your profile. You can do this in your settings:

github.com/YOUR_PROFILE --> Settings --> Profile

Then scroll down to "Contributions" and check the box that says "Include private contributions on my profile".

Hope that helps.
Reply
Â 
nirav97120 profile image
â€¢
Dec 16

Awesome My github profile
Reply
Â 
wkylin profile image
â€¢
May 1

Here's mine:
github.com/wkylin
Reply
Â 
laurasiiia profile image
â€¢
Jan 3 â€¢ Edited on Jan 3

Hi, i did everything right and even got the "build" status. But no output branch was created... why is that? Can someone help me? github.com/laurasiiia
Reply
Â 
mishmanners profile image
â€¢
Jan 4

I assume you're working off this folder: github.com/laurasiiia/laurasiiia/b...

Since you've got a newer repo (mine account was set up a number of years ago), you have the default branch set to "main". You might need to change the code to be "main" instead of "master".

I created a PR for you: github.com/laurasiiia/laurasiiia/p...
(run it and see if that works)... it might not but worth a shot. Feel free to jump in other people ğŸ˜„
Reply
Â 
phuocantd profile image
â€¢
Jun 1

How to auto build workflow everyday
Reply
Â 
adityamangal1 profile image
â€¢
Jul 22 '21

Awesome Tutorial! ğŸ
Reply
Â 
wisnuaero profile image
â€¢
Dec 7

here's mine - github.com/wisnuaero
Reply
Â 
brayheart profile image
â€¢
Nov 10

Thanks for making this guide!
Reply
Â 
matheusroichman profile image
â€¢
Nov 2

Mine is not showing all the contributions :(
github.com/MatheusRoichman/Matheus...
Reply
Â 
smartmayukh profile image
â€¢
Jul 1

Works great !!!!!!!! Here's mine

github.com/Smartmayukh
Reply
View full discussion (25 comments)
Code of Conduct â€¢ Report abuse
ğŸŒš Friends don't let friends browse without dark mode.

Sorry, it's true.
Read next
enteio profile image
ente Auth

ente - Dec 10
whoisryosuke profile image
GLTF Animations in wgpu and Rust

Ryosuke - Dec 14
devneagu profile image
[How to] write abstract functions in JS

devneagu - Dec 10
codewithsadee profile image
Make Mysterious Shape from SHADOW ğŸ¤¯

Sadee - Dec 9
Michelle Mannering
Developer Advocate | Hackathon Queen | International Speaker

    Location
    Australia
    Education
    The University of Melbourne
    Work
    Developer Advocate at GitHub
    Joined
    May 29, 2020

More from Michelle Mannering
Why 'release' a project? How to automate releases
#opensource #productivity #github #tooling
How to get ready for Hacktoberfest 2022
#hacktoberfest #opensource #tutorial
GitHub's non-code features
#github #beginners #productivity #opensource


# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mishmanners
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

DEV Community ğŸ‘©â€ğŸ’»ğŸ‘¨â€ğŸ’» â€” A constructive and inclusive social network for software developers. With you every step of your journey.

Built on Forem â€” the open source software that powers DEV and other inclusive communities.

Made with love and Ruby on Rails. DEV Community ğŸ‘©â€ğŸ’»ğŸ‘¨â€ğŸ’» Â© 2016 - 2022.
